// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EjercicioLinqCompletoBBDD;

#nullable disable

namespace _26_EjercicioLinqCompleto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220620144135_primera_migracion")]
    partial class primera_migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PoblacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoblacionId");

                    b.ToTable("Alunnos");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Anyo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clases");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ClaseId");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Poblacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Poblaciones");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PoblacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("PoblacionId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Alumno", b =>
                {
                    b.HasOne("EjercicioLinqCompletoBBDD.Entidades.Poblacion", "Poblacion")
                        .WithMany("Alumnos")
                        .HasForeignKey("PoblacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poblacion");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Nota", b =>
                {
                    b.HasOne("EjercicioLinqCompletoBBDD.Entidades.Alumno", "Alumno")
                        .WithMany("Notas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EjercicioLinqCompletoBBDD.Entidades.Clase", "Clase")
                        .WithMany("Notas")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Profesor", b =>
                {
                    b.HasOne("EjercicioLinqCompletoBBDD.Entidades.Clase", "Clase")
                        .WithMany("Profesores")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EjercicioLinqCompletoBBDD.Entidades.Poblacion", "Poblacion")
                        .WithMany("Profesores")
                        .HasForeignKey("PoblacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Poblacion");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Alumno", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Clase", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("EjercicioLinqCompletoBBDD.Entidades.Poblacion", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Profesores");
                });
#pragma warning restore 612, 618
        }
    }
}
